cleaning up build script, adding some variable and file checking logic.

diff --git a/java/java-build b/java/java-build
--- a/java/java-build
+++ b/java/java-build
@@ -2,32 +2,59 @@
  
 FAILURE=1
 SUCCESS=0
- 
-APP_HOME=/your/app/home/path/pubnub-java/
+
+# Set APP_HOME to PUBNUB_GIT_ROOT/java
+APP_HOME=/home/geremy/pubnub-api/java
+
 LIB=${APP_HOME}/lib/
- 
 CP=${LIB}async-http-client-1.6.5-shaded.jar:${LIB}slf4j-nop-1.6.2.jar:src/:.
+
+# cleaning up
+if [ -f "$APP_HOME/src/tests/PubnubUnitTest.java" ]; then
+    echo -e "Cleaning up..."
+    rm src/tests/*.class
+fi
+
+
+# Check to see if we look good...
+
+if [ -z "$JAVA_HOME" ]; then
+    echo "Need to set JAVA_HOME environmental variable."
+    exit 1
+fi  
+
  
-APP_JAVA_HOME=/opt/jdk
+if [ ! -f "$JAVA_HOME/bin/javac" ]; then
+    echo "Can't find javac in JAVA_HOME/bin."
+    exit 1
+fi
+
+if [ ! -f "$APP_HOME/src/tests/PubnubUnitTest.java" ]; then
+    echo "Please edit this build script and verify APP_HOME is valid."
+    exit 1
+fi
+
 cd ${APP_HOME}
 echo -e "Building..."
 
-${APP_JAVA_HOME}/bin/javac -cp "${CP}" src/tests/PubnubUnitTest.java
+${JAVA_HOME}/bin/javac -cp "${CP}" src/tests/PubnubUnitTest.java
 
 if [ $? -ne 0 ]
 then
     echo "Test failed during compilation"
     exit ${FAILURE}
 fi
- 
+
+echo -e "Build succeeded."
+echo 
 echo -e "Running..."
-${APP_JAVA_HOME}/bin/java -cp "${CP}" src/tests/PubnubUnitTest
+${JAVA_HOME}/bin/java -cp "${CP}" src/tests/PubnubUnitTest
 
 if [ $? -ne 0 ]
 then
-    echo "Test failed during run"
+    echo "Tests failed."
     exit ${FAILURE}
 fi
 
-echo "Test run successfully"
+echo "Tests ran successfully!"
 exit ${SUCCESS}
